using Content.Shared._ALTSpace.Roadmap;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;
using Robust.Client.Graphics; // Для StyleBoxFlat
using Robust.Shared.IoC;
using System.Numerics;

namespace Content.Client._ALTSpace.Lobby.Roadmap
{
    [GenerateTypedNameReferences]
    public sealed partial class RoadmapWindow : DefaultWindow
    {
        public RoadmapWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            PopulateList();
        }

        private void PopulateList()
        {
            var protoManager = IoCManager.Resolve<IPrototypeManager>();
            RoadmapList.DisposeAllChildren();

            foreach (var proto in protoManager.EnumeratePrototypes<RoadmapPrototype>())
            {
                var container = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    SeparationOverride = 4
                };

                // Заголовок
                container.AddChild(new Label
                {
                    Text = $"{proto.Title} ({proto.Category})",
                    StyleClasses = { "LabelHeading" }
                });

                var description = new RichTextLabel
                {
                    Margin = new Thickness(5, 0)
                };
                description.SetMessage(proto.Description);
                container.AddChild(description);

                var bar = new ProgressBar
                {
                    MinValue = 0,
                    MaxValue = 100,
                    Value = proto.Progress,
                    MinSize = new Vector2(0, 20)
                };
                bar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#fddb00") };
                container.AddChild(bar);
                container.AddChild(new Content.Client.UserInterface.Controls.HLine
                {
                    Thickness = 1,
                    Color = Color.DimGray
                });

                RoadmapList.AddChild(container);
            }
        }
    }
}